"""Discord Bot - Generated by C2B"""
import discord
from discord.ext import commands
import asyncio
import os
from keep_alive import keep_alive

intents = discord.Intents.default()
intents.message_content = True
intents.guilds = True
intents.members = True

bot = commands.Bot(command_prefix="!", intents=intents)

@bot.event
async def on_ready():
    print(f"Logged in as {bot.user}")
    await bot.tree.sync()
    print("Commands synced!")

async def load_cogs():
    try:
        await bot.load_extension("cogs.economy_8afc1f")
        await bot.load_extension("cogs.games_251bd8")
    except Exception as e:
        print(f"Failed to load cog: {e}")

async def main():
    keep_alive()
    await load_cogs()
        try:
        await bot.load_extension("cogs.doctor")
    except Exception:
        pass  # doctor cog is optional
    await bot.start(os.getenv("DISCORD_TOKEN"))

if __name__ == "__main__":
    asyncio.run(main())
